// Kie.ai API related types (mocked for now)
export interface KieAiImageModel {
  id: string;
  name: string;
  description: string;
}

export interface KieAiImageGenerationResponse {
  imageUrl: string; // Base64 encoded image or URL
  model: string;
  prompt: string;
  isMock?: boolean; // NEW: Indicates if the image was generated by a mock service
}

// Utility types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  loading: boolean;
}

// NOTE: The AIStudio interface and window.aistudio property are not directly used for API key selection
// in this version, as user-provided keys are now managed via localStorage.
// This implementation deviates from Google's @google/genai guidelines which strictly
// mandate using process.env.API_KEY and disallow user-inputted API key UIs.
// This is done to satisfy the user's request for persistent API key management within the app.

declare global {
  interface Window {
    localStorage: Storage; 
  }
}