import { GoogleGenAI, GenerateContentResponse, Part } from '@google/genai';
import { KieAiImageGenerationResponse, KieAiImageModel, ReferenceImage } from '../types';

/**
 * Generates a data URL for a simple SVG placeholder image indicating it's a mock.
 */
const getMockImageUrl = (width: number, height: number, seed?: number): string => {
  const svg = `<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
    <rect width="${width}" height="${height}" fill="#cccccc"/>
    <text x="50%" y="50%" font-family="Arial, sans-serif" font-size="${Math.min(width, height) / 8}" fill="#333333" text-anchor="middle" dominant-baseline="middle">MOCK IMAGE</text>
    <text x="50%" y="70%" font-family="Arial, sans-serif" font-size="${Math.min(width, height) / 10}" fill="#333333" text-anchor="middle" dominant-baseline="middle">${seed ? `Seed: ${seed}` : ''}</text>
  </svg>`;
  return `data:image/svg+xml;base64,${btoa(svg)}`;
};

/**
 * Uploads a base64 image to Kie.ai to get a temporary URL.
 * Required for models like Flux-2 that expect image URLs.
 */
async function uploadImageToKieAi(apiKey: string, base64Data: string, mimeType: string, originalFileName?: string): Promise<string> {
  // Correct Kie.ai File Upload API base URL and endpoint for Base64 upload
  const uploadEndpoint = 'https://kieai.redpandaai.co/api/file-base64-upload'; 
  
  // Construct the full data URL as required by Kie.ai's base64 upload API
  const fullBase64Data = `data:${mimeType};base64,${base64Data}`;
  
  console.log(`[Kie.ai] Starting image upload. API Key present: ${!!apiKey}`);

  const payload: any = {
    base64Data: fullBase64Data,
    uploadPath: 'images', // A default path for uploaded images
  };
  // Use originalFileName if provided, otherwise generate a generic one
  if (originalFileName) {
    payload.fileName = originalFileName;
  } else {
    payload.fileName = `uploaded-image.${mimeType.split('/')[1] || 'png'}`; 
  }

  const response = await fetch(uploadEndpoint, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json' // Correct Content-Type for JSON payload
    },
    body: JSON.stringify(payload) // Send JSON body
  });

  const result = await response.json();
  if (!response.ok || result.code !== 200) {
    console.error('[Kie.ai] Image upload failed:', result);
    throw new Error(`Kie.ai 이미지 업로드 실패: API 호출 오류. (URL: ${uploadEndpoint}, 상태: ${response.status}) 메시지: ${result.msg || JSON.stringify(result)}`);
  }

  console.log('[Kie.ai] Image uploaded successfully:', result.data.fileUrl);
  return result.data.fileUrl; // Should return fileUrl from data
}

/**
 * Gets a direct download URL for a Kie.ai hosted image.
 *
 * @param apiKey The Kie.ai API key.
 * @param imageUrl The URL of the image generated by Kie.ai.
 * @returns A promise that resolves with the actual direct download URL.
 */
export async function getKieAiDirectDownloadUrl(apiKey: string, imageUrl: string): Promise<string> {
  const downloadUrlEndpoint = 'https://api.kie.ai/api/v1/common/download-url';
  
  if (!apiKey) {
    throw new Error('Kie.ai API 키가 제공되지 않아 Kie.ai 다운로드 URL을 생성할 수 없습니다.');
  }

  console.log(`[Kie.ai] Requesting direct download URL for: ${imageUrl}. API Key present: ${!!apiKey}`);

  try {
    const response = await fetch(downloadUrlEndpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ url: imageUrl })
    });

    const result = await response.json();

    if (!response.ok || result.code !== 200) {
      console.error('[Kie.ai] Get Download URL failed:', result);
      let errorMessage = result.msg || `알 수 없는 오류 (Code: ${result.code || response.status})`;
      if (errorMessage.includes('access permissions') || errorMessage.includes('invalid api key')) {
          errorMessage = `Kie.ai API 키가 유효하지 않거나 접근 권한이 없습니다. Kie.ai 대시보드(https://kie.ai/api-key)에서 API 키를 확인해주세요.`;
      } else if (response.status === 401) { // Explicit 401 for unauthorized
          errorMessage = `Kie.ai API 키 인증에 실패했습니다. 올바른 키를 입력해주세요.`;
      }
      throw new Error(`Kie.ai 다운로드 URL 생성 실패: ${errorMessage}`);
    }

    if (!result.data) {
      console.error('[Kie.ai] Get Download URL succeeded but no URL in data:', result);
      throw new Error('Kie.ai 다운로드 URL 생성 실패: 응답에서 유효한 URL을 찾을 수 없습니다.');
    }

    console.log(`[Kie.ai] Direct download URL obtained: ${result.data}`);
    return result.data;
  } catch (error: any) {
    console.error('[Kie.ai] Error during getKieAiDirectDownloadUrl:', error);
    if (error instanceof Error) {
      throw error; // Re-throw specific errors already generated
    } else {
      throw new Error(`Kie.ai 다운로드 URL을 가져오는 중 네트워크/알 수 없는 오류 발생: ${error.message || JSON.stringify(error)}`);
    }
  }
}


/**
 * Handles the asynchronous workflow for Kie.ai job-based APIs (Seedream, etc.)
 * by creating a task and then polling for its status.
 */
async function callKieAiGenericJobApi(
  apiKey: string,
  modelName: string, // e.g., 'bytedance/seedream-v4-text-to-image' or 'flux-2/pro-text-to-image' or 'z-image' or 'grok-imagine/text-to-image' or 'qwen/image-to-image'
  inputPayload: any,
  maxWaitTimeMs: number = 300000, // 5 minutes
): Promise<string[]> {
  const kieAiBaseUrl = 'https://api.kie.ai'; // This base URL is correct for jobs/createTask
  const createTaskUrl = `${kieAiBaseUrl}/api/v1/jobs/createTask`;
  const getTaskDetailUrl = `${kieAiBaseUrl}/api/v1/jobs/recordInfo`; 

  const headers = {
    'Authorization': `Bearer ${apiKey}`,
    'Content-Type': 'application/json'
  };

  console.log(`[Kie.ai Generic Job API - ${modelName}] Submitting task. API Key present: ${!!apiKey}`);
  console.log('[Kie.ai Generic Job API] Payload:', inputPayload);

  // 1. Create Task
  const createResponse = await fetch(createTaskUrl, {
    method: 'POST',
    headers: headers,
    body: JSON.stringify({
      model: modelName,
      input: inputPayload
    })
  });

  const createResult = await createResponse.json();
  if (!createResponse.ok || createResult.code !== 200) {
    console.error(`[Kie.ai Generic Job API - ${modelName}] Task creation failed:`, createResult);
    
    // Check for specific 'access permissions' error
    if (createResult.msg && typeof createResult.msg === 'string' && (createResult.msg.includes('access permissions') || createResult.msg.includes('invalid api key'))) {
      throw new Error(
        `${modelName} 작업 생성 실패: Kie.ai API 키가 유효하지 않거나 '${modelName}' 모델에 대한 접근 권한이 없습니다. Kie.ai 대시보드(https://kie.ai/api-key)에서 API 키를 확인해주세요. 오류: ${createResult.msg}`
      );
    } else {
      throw new Error(`${modelName} 작업 생성 실패: ${createResult.msg || JSON.stringify(createResult)}`);
    }
  }
  
  const taskId = createResult.data?.taskId;
  if (!taskId) {
    console.error(`[Kie.ai Generic Job API - ${modelName}] Task creation succeeded but no taskId was returned:`, createResult);
    throw new Error(`${modelName} Task creation succeeded but no taskId was returned.`);
  }
  
  console.log(`[Kie.ai Generic Job API - ${modelName}] Task ID: ${taskId}. Starting polling for status from ${getTaskDetailUrl}?taskId=${taskId}...`);

  // 2. Poll for Status
  const startTime = Date.now();
  while (Date.now() - startTime < maxWaitTimeMs) {
    await new Promise(resolve => setTimeout(resolve, 5000)); // Poll every 5 seconds

    const statusResponse = await fetch(`${getTaskDetailUrl}?taskId=${taskId}`, {
      method: 'GET',
      headers: { 'Authorization': `Bearer ${apiKey}` }
    });
    
    const statusResult = await statusResponse.json();
    console.debug(`[Kie.ai Generic Job API - ${modelName} Polling Response]:`, statusResult);

    if (!statusResponse.ok || statusResult.code !== 200) {
      console.error(`[Kie.ai Generic Job API - ${modelName}] Status check failed (HTTP ${statusResponse.status}):`, statusResult);
      throw new Error(`${modelName} Status check failed (HTTP ${statusResponse.status}): ${statusResult.msg || JSON.stringify(statusResult)}`);
    }

    const taskData = statusResult.data;
    if (!taskData) {
      console.warn(`[Kie.ai Generic Job API - ${modelName}] Polling returned 200 but no data in taskData.`);
      continue;
    }

    // Seedream API uses 'state' field, not 'successFlag'.
    // Possible states: 'waiting', 'queuing', 'generating', 'success', 'fail'
    const taskState = taskData.state;

    if (taskState === 'success') {
      console.log(`[Kie.ai Generic Job API - ${modelName}] Generation Success!`);
      
      let parsedResultJson = null;
      if (taskData.resultJson && typeof taskData.resultJson === 'string') {
        try {
          parsedResultJson = JSON.parse(taskData.resultJson);
        } catch (e) {
          console.error(`[Kie.ai Generic Job API - ${modelName}] Failed to parse resultJson:`, e);
        }
      }

      // Prioritize parsing resultJson, then fallback to other properties
      const resultUrls = 
        parsedResultJson?.resultUrls ||
        taskData.response?.resultUrls || // Fallback if resultJson failed or wasn't primary source
        taskData.resultUrls || 
        taskData.response?.result_urls || 
        taskData.response?.images || 
        taskData.images || 
        taskData.response?.output ||
        (Array.isArray(taskData.response) ? taskData.response : null); 
      
      if (Array.isArray(resultUrls) && resultUrls.length > 0) {
        return resultUrls;
      }
      
      console.error(`[Kie.ai Generic Job API - ${modelName}] API reported success but no result images were found:`, taskData);
      throw new Error(`${modelName} API reported success but no result images were found in the response.`);
    } else if (taskState === 'fail') { // Check for 'fail' state
      console.error(`[Kie.ai Generic Job API - ${modelName}] Generation failed from API:`, taskData);
      const failMsg = taskData.failMsg || taskData.errorMessage || taskData.error_message || 'Unknown API Error';
      let userFriendlyFailMsg = failMsg;
      if (failMsg.includes('internal error')) {
          userFriendlyFailMsg += ". Kie.ai 서버 내부 오류입니다. 잠시 후 다시 시도하거나 Kie.ai 지원팀에 문의해주세요.";
      } else if (failMsg.includes('invalid api key') || failMsg.includes('access permissions')) { // Added specific check for invalid API key from Kie.ai
          userFriendlyFailMsg = `Kie.ai API 키가 유효하지 않거나 '${modelName}' 모델에 대한 접근 권한이 없습니다. 올바른 키를 입력해주세요.`;
      }
      throw new Error(`${modelName} Generation failed: ${userFriendlyFailMsg}`); // Use failMsg
    } else if (['waiting', 'queuing', 'generating'].includes(taskState)) {
      // Continue polling for these states
      console.log(`[Kie.ai Generic Job API - ${modelName}] Status: ${taskData.state}. Progress: ${taskData.progress || 'Processing...'}`);
    } else {
      // Unknown state, log a warning and continue polling (or decide to throw error)
      console.warn(`[Kie.ai Generic Job API - ${modelName}] Unknown task state: ${taskState}. Continuing to poll.`);
    }
  }

  throw new Error(`${modelName} Generation timed out.`);
}

/**
 * Handles the asynchronous workflow for Kie.ai 4o Image API.
 */
async function call4oImageApi(
  apiKey: string,
  prompt: string,
  size: string,
  nVariants: number = 1,
  isEnhance: boolean = false,
  referenceImageUrls?: string[] | null, // CHANGED: Now expects array of URLs
  maxWaitTimeMs: number = 300000,
): Promise<string[]> {
  const baseUrl = 'https://api.kie.ai/api/v1/gpt4o-image';
  const headers = {
    'Authorization': `Bearer ${apiKey}`,
    'Content-Type': 'application/json'
  };

  console.log(`[Kie.ai 4o Image] Submitting generation task. API Key present: ${!!apiKey}`);
  const generateResponse = await fetch(`${baseUrl}/generate`, {
    method: 'POST',
    headers: headers,
    body: JSON.stringify({
      prompt: prompt,
      size: size,
      nVariants: nVariants,
      isEnhance: isEnhance,
      ...(referenceImageUrls && referenceImageUrls.length > 0 && {reference_images: referenceImageUrls}), // Pass reference images array
    })
  });

  const generateResult = await generateResponse.json();
  if (!generateResponse.ok || generateResult.code !== 200) {
    console.error('[Kie.ai 4o Image] Generation failed:', generateResult);
    let errorMessage = generateResult.msg || JSON.stringify(generateResult);
    if (errorMessage.includes('invalid api key')) { // Specific check for invalid API key
        errorMessage = `Kie.ai API 키가 유효하지 않습니다. 올바른 키를 입력해주세요.`;
    } else if (errorMessage.includes('internal error')) {
        errorMessage += ". Kie.ai 서버 내부 오류입니다. 잠시 후 다시 시도하거나 Kie.ai 지원팀에 문의해주세요.";
    }
    throw new Error(`4o Image API failed: ${errorMessage}`);
  }
  const taskId = generateResult.data.taskId;
  if (!taskId) { // Add check for taskId existence
    console.error('[Kie.ai 4o Image] Generation succeeded but no taskId was returned:', generateResult);
    throw new Error('4o Image Generation succeeded but no taskId was returned.');
  }
  console.log(`[Kie.ai 4o Image] Task ID: ${taskId}. Starting polling...`);

  const startTime = Date.now();
  while (Date.now() - startTime < maxWaitTimeMs) {
    await new Promise(resolve => setTimeout(resolve, 5000));

    const statusResponse = await fetch(`${baseUrl}/record-info?taskId=${taskId}`, {
      method: 'GET',
      headers: { 'Authorization': `Bearer ${apiKey}` }
    });
    const statusResult = await statusResponse.json();
    console.debug('[Kie.ai 4o Image] Polling Response:', statusResult);

    if (!statusResponse.ok || statusResult.code !== 200) {
      console.error('[Kie.ai 4o Image] Status check failed:', statusResult);
      let errorMessage = statusResult.msg || JSON.stringify(statusResult);
      if (errorMessage.includes('invalid api key')) { // Specific check for invalid API key
          errorMessage = `Kie.ai API 키가 유효하지 않습니다. 올바른 키를 입력해주세요.`;
      } else if (errorMessage.includes('internal error')) {
          errorMessage += ". Kie.ai 서버 내부 오류입니다. 잠시 후 다시 시도하거나 Kie.ai 지원팀에 문의해주세요.";
      }
      throw new Error(`4o Image Status check failed: ${errorMessage}`);
    }

    const taskData = statusResult.data;
    if (taskData.successFlag === 1) {
      console.log('[Kie.ai 4o Image] Generation Success!');
      const resultUrls = taskData.response?.resultUrls;
      if (Array.isArray(resultUrls) && resultUrls.length > 0) return resultUrls;
      
      console.error('[Kie.ai 4o Image] API reported success but no resultUrls were found:', taskData);
      throw new Error('4o Image API Success flag 1 but no resultUrls.');
    } else if (taskData.successFlag === 2) {
      console.error('[Kie.ai 4o Image] Generation failed from API:', taskData);
      const errorMessage = taskData.errorMessage || 'Unknown Error';
      if (errorMessage.includes('invalid api key')) { // Specific check for invalid API key
          throw new Error(`4o Image Generation failed: ${errorMessage}. Kie.ai API 키가 유효하지 않습니다. 올바른 키를 입력해주세요.`);
      } else if (errorMessage.includes('internal error')) {
          throw new Error(`4o Image Generation failed: ${errorMessage}. Kie.ai 서버 내부 오류입니다. 잠시 후 다시 시도하거나 Kie.ai 지원팀에 문의해주세요.`);
      }
      throw new Error(`4o Image Generation failed: ${errorMessage}`);
    }
    console.log(`[Kie.ai 4o Image] Progress: ${taskData.progress || 'Processing...'}`);
  }
  throw new Error('4o Image API Timeout');
}

/**
 * Handles the asynchronous workflow for Kie.ai Flux Kontext API.
 * Uses /api/v1/flux/kontext/generate and /api/v1/flux/kontext/record-info.
 * NOTE: This function is kept for reference but 'kie-flux-2-pro' now uses callKieAiGenericJobApi.
 */
async function callFluxKontextApi(
  apiKey: string,
  modelVersion: string, // e.g., 'flux-kontext-pro' or 'flux-kontext-max'
  prompt: string,
  aspectRatio: string,
  resolution: string, // e.g., '1K', '2K', '4K'
  imageUrlToEdit?: string | null, // For image editing
  referenceImageUrls?: string[] | null, // CHANGED: Now expects array of URLs for I2I generation
  maxWaitTimeMs: number = 300000, // 5 minutes
): Promise<string[]> {
  const baseUrl = 'https://api.kie.ai/api/v1/flux/kontext';
  const generateUrl = `${baseUrl}/generate`;
  const recordInfoUrl = `${baseUrl}/record-info`;

  const headers = {
    'Authorization': `Bearer ${apiKey}`,
    'Content-Type': 'application/json'
  };

  console.log(`[Kie.ai Flux Kontext API - ${modelVersion}] Submitting task. API Key present: ${!!apiKey}`);
  const inputPayload: any = {
    prompt: prompt,
    aspect_ratio: aspectRatio,
    resolution: resolution,
    model: modelVersion,
  };

  if (imageUrlToEdit) {
    inputPayload.image_url = imageUrlToEdit; // For editing
  } else if (referenceImageUrls && referenceImageUrls.length > 0) { // CHANGED: check length
    inputPayload.reference_image_urls = referenceImageUrls; // For I2I generation
  }

  console.log('[Kie.ai Flux Kontext API] Payload:', inputPayload);

  // 1. Generate Task
  const generateResponse = await fetch(generateUrl, {
    method: 'POST',
    headers: headers,
    body: JSON.stringify(inputPayload)
  });

  const generateResult = await generateResponse.json();
  if (!generateResponse.ok || generateResult.code !== 200) {
    console.error(`[Kie.ai Flux Kontext API - ${modelVersion}] Generation failed:`, generateResult);
    let errorMessage = generateResult.msg || JSON.stringify(generateResult);
    if (errorMessage.includes('invalid api key')) { // Specific check for invalid API key
        errorMessage = `Kie.ai API 키가 유효하지 않습니다. 올바른 키를 입력해주세요.`;
    } else if (errorMessage.includes('internal error')) {
        errorMessage += ". Kie.ai 서버 내부 오류입니다. 잠시 후 다시 시도하거나 Kie.ai 지원팀에 문의해주세요.";
    }
    throw new Error(`Flux Kontext API failed: ${errorMessage}`);
  }
  
  const taskId = generateResult.data?.taskId;
  if (!taskId) {
    console.error(`[Kie.ai Flux Kontext API - ${modelVersion}] Generation succeeded but no taskId was returned:`, generateResult);
    throw new Error(`${modelVersion} Generation succeeded but no taskId was returned.`);
  }
  
  console.log(`[Kie.ai Flux Kontext API - ${modelVersion}] Task ID: ${taskId}. Starting polling for status from ${recordInfoUrl}?taskId=${taskId}...`);

  // 2. Poll for Status
  const startTime = Date.now();
  while (Date.now() - startTime < maxWaitTimeMs) {
    await new Promise(resolve => setTimeout(resolve, 5000)); // Poll every 5 seconds

    const statusResponse = await fetch(`${recordInfoUrl}?taskId=${taskId}`, {
      method: 'GET',
      headers: { 'Authorization': `Bearer ${apiKey}` }
    });
    
    const statusResult = await statusResponse.json();
    console.debug(`[Kie.ai Flux Kontext API - ${modelVersion} Polling Response]:`, statusResult);

    if (!statusResponse.ok || statusResult.code !== 200) {
      console.error(`[Kie.ai Flux Kontext API - ${modelVersion}] Status check failed (HTTP ${statusResponse.status}):`, statusResult);
      let errorMessage = statusResult.msg || JSON.stringify(statusResult);
      if (errorMessage.includes('invalid api key')) { // Specific check for invalid API key
          errorMessage = `Kie.ai API 키가 유효하지 않습니다. 올바른 키를 입력해주세요.`;
      } else if (errorMessage.includes('internal error')) {
          errorMessage += ". Kie.ai 서버 내부 오류입니다. 잠시 후 다시 시도하거나 Kie.ai 지원팀에 문의해주세요.";
      }
      throw new Error(`Flux Kontext API failed (HTTP ${statusResponse.status}): ${errorMessage}`);
    }

    const taskData = statusResult.data;
    if (!taskData) {
      console.warn(`[Kie.ai Flux Kontext API - ${modelVersion}] Polling returned 200 but no data in taskData.`);
      continue;
    }

    // successFlag: 0 (Pending/Generating), 1 (Success), 2 (Failed)
    if (taskData.successFlag === 1) {
      console.log(`[Kie.ai Flux Kontext API - ${modelVersion}] Generation Success!`);
      
      let parsedResultJson = null;
      if (taskData.resultJson && typeof taskData.resultJson === 'string') {
        try {
          parsedResultJson = JSON.parse(taskData.resultJson);
        } catch (e) {
          console.error(`[Kie.ai Flux Kontext API - ${modelVersion}] Failed to parse resultJson:`, e);
        }
      }

      const resultUrls = 
        parsedResultJson?.resultUrls ||
        taskData.response?.resultUrls || 
        taskData.resultUrls || 
        taskData.response?.result_urls || 
        taskData.response?.images || 
        taskData.images || 
        taskData.response?.output ||
        (Array.isArray(taskData.response) ? taskData.response : null); 
      
      if (Array.isArray(resultUrls) && resultUrls.length > 0) {
        return resultUrls;
      }
      
      console.error(`[Kie.ai Flux Kontext API - ${modelVersion}] API reported success but no result images were found:`, taskData);
      throw new Error(`${modelVersion} API reported success but no result images were found in the response.`);
    } else if (taskData.successFlag === 2) {
      console.error(`[Kie.ai Flux Kontext API - ${modelVersion}] Generation failed from API:`, taskData);
      const errorMessage = taskData.errorMessage || taskData.error_message || 'Unknown API Error';
       if (errorMessage.includes('invalid api key')) { // Specific check for invalid API key
          throw new Error(`${modelVersion} Generation failed: ${errorMessage}. Kie.ai API 키가 유효하지 않습니다. 올바른 키를 입력해주세요.`);
      } else if (errorMessage.includes('internal error')) {
          throw new Error(`Kie.ai Generation failed: ${errorMessage}. Kie.ai 서버 내부 오류입니다. 잠시 후 다시 시도하거나 Kie.ai 지원팀에 문의해주세요.`);
      }
      throw new Error(`${modelVersion} Generation failed: ${errorMessage}`);
    }

    console.log(`[Kie.ai Flux Kontext API - ${modelVersion}] Progress: ${taskData.progress || 'Processing...'}`);
  }

  throw new Error(`${modelVersion} Generation timed out.`);
}

/**
 * Handles the asynchronous workflow for Kie.ai Midjourney API.
 * Uses /api/v1/mj/generate and /api/v1/mj/record-info.
 */
async function callKieAiMidjourneyApi(
  apiKey: string,
  prompt: string,
  aspectRatio: string,
  speed: string = 'fast', // Hardcoded as per ui.py snippet
  maxWaitTimeMs: number = 300000, // 5 minutes
): Promise<string[]> {
  const baseUrl = 'https://api.kie.ai/api/v1/mj';
  const generateUrl = `${baseUrl}/generate`;
  const recordInfoUrl = `${baseUrl}/record-info`;

  const headers = {
    'Authorization': `Bearer ${apiKey}`,
    'Content-Type': 'application/json'
  };

  console.log(`[Kie.ai Midjourney] Submitting generation task. API Key present: ${!!apiKey}`);
  const inputPayload: any = {
    taskType: 'mj_txt2img', // As per ui.py snippet
    prompt: prompt,
    speed: speed,
    aspectRatio: aspectRatio, // Dynamic aspect ratio from frontend
  };

  console.log('[Kie.ai Midjourney] Payload:', inputPayload);

  // 1. Generate Task
  const generateResponse = await fetch(generateUrl, {
    method: 'POST',
    headers: headers,
    body: JSON.stringify(inputPayload)
  });

  const createResult = await generateResponse.json();
  if (!generateResponse.ok || createResult.code !== 200) {
    console.error('[Kie.ai Midjourney] Generation failed:', createResult);
    let errorMessage = createResult.msg || JSON.stringify(createResult);
    if (errorMessage.includes('access permissions') || errorMessage.includes('invalid api key')) {
        errorMessage = `Kie.ai Midjourney 모델에 대한 접근 권한이 없거나 유효하지 않습니다. Kie.ai 대시보드(https://kie.ai/api-key)에서 API 키를 확인해주세요.`;
    } else if (errorMessage.includes('internal error')) {
        errorMessage += ". Kie.ai 서버 내부 오류입니다. 잠시 후 다시 시도하거나 Kie.ai 지원팀에 문의해주세요.";
    }
    throw new Error(`Midjourney API failed: ${errorMessage}`);
  }
  
  const taskId = createResult.data?.taskId;
  if (!taskId) {
    console.error('[Kie.ai Midjourney] Generation succeeded but no taskId was returned: ', createResult);
    throw new Error('Midjourney Generation succeeded but no taskId was returned.');
  }
  
  console.log(`[Kie.ai Midjourney] Task ID: ${taskId}. Starting polling for status from ${recordInfoUrl}?taskId=${taskId}...`);

  // 2. Poll for Status
  const startTime = Date.now();
  while (Date.now() - startTime < maxWaitTimeMs) {
    await new Promise(resolve => setTimeout(resolve, 5000)); // Poll every 5 seconds

    const statusResponse = await fetch(`${recordInfoUrl}?taskId=${taskId}`, {
      method: 'GET',
      headers: { 'Authorization': `Bearer ${apiKey}` }
    });
    
    const statusResult = await statusResponse.json();
    console.debug(`[Kie.ai Midjourney Polling Response]:`, statusResult);

    if (!statusResponse.ok || statusResult.code !== 200) {
      console.error(`[Kie.ai Midjourney] Status check failed (HTTP ${statusResponse.status}):`, statusResult);
      let errorMessage = statusResult.msg || JSON.stringify(statusResult);
       if (errorMessage.includes('access permissions') || errorMessage.includes('invalid api key')) {
          errorMessage = `Kie.ai Midjourney 모델에 대한 접근 권한이 없거나 유효하지 않습니다. Kie.ai 대시보드(https://kie.ai/api-key)에서 API 키를 확인해주세요.`;
      } else if (errorMessage.includes('internal error')) {
          errorMessage += ". Kie.ai 서버 내부 오류입니다. 잠시 후 다시 시도하거나 Kie.ai 지원팀에 문의해주세요.";
      }
      throw new Error(`Midjourney Status check failed (HTTP ${statusResponse.status}): ${errorMessage}`);
    }

    const taskData = statusResult.data;
    if (!taskData) {
      console.warn('[Kie.ai Midjourney] Polling returned 200 but no data in taskData.');
      continue;
    }

    // successFlag: 0 (Pending/Generating), 1 (Success), 2 (Failed)
    // The ui.py parser: lambda data: data.get("resultInfoJson", {}).get("resultUrls", [{}])[0].get("resultUrl")
    if (taskData.successFlag === 1) {
      console.log(`[Kie.ai Midjourney] Generation Success!`);
      
      const resultInfoJson = taskData.resultInfoJson;
      const resultUrls = resultInfoJson?.resultUrls;
      
      if (Array.isArray(resultUrls) && resultUrls.length > 0 && resultUrls[0]?.resultUrl) {
        return [resultUrls[0].resultUrl]; // Return as an array of strings
      }
      
      console.error('Kie.ai Midjourney API reported success but no result images were found:', taskData); // Fixed SyntaxError here
      throw new Error('Midjourney API reported success but no result images were found in the response.');
    } else if (taskData.successFlag === 2) {
      console.error('Kie.ai Midjourney] Generation failed from API:', taskData);
      const errorMessage = taskData.errorMessage || taskData.error_message || 'Unknown API Error';
      if (errorMessage.includes('access permissions') || errorMessage.includes('invalid api key')) {
          throw new Error(`Midjourney Generation failed: ${errorMessage}. Kie.ai Midjourney 모델에 대한 접근 권한이 없거나 유효하지 않습니다. Kie.ai 대시보드(https://kie.ai/api-key)에서 API 키를 확인해주세요.`);
      } else if (errorMessage.includes('internal error')) {
          throw new Error(`Midjourney Generation failed: ${errorMessage}. Kie.ai 서버 내부 오류입니다. 잠시 후 다시 시도하거나 Kie.ai 지원팀에 문의해주세요.`);
      }
      throw new Error(`Midjourney Generation failed: ${errorMessage}`);
    }

    console.log(`[Kie.ai Midjourney] Progress: ${taskData.progress || 'Processing...'}`);
  }

  throw new Error('Midjourney API Timeout');
}

/**
 * Helper to map app aspectRatio and imageQuality to Qwen's image_size options.
 */
export const mapToQwenImageSize = (appAspectRatio: string, imageQuality: string): string => {
  const isHd = imageQuality === '2K' || imageQuality === '4K';

  switch (appAspectRatio) {
    case '1:1':
      return isHd ? 'square_hd' : 'square';
    case '16:9':
    case '21:9': // Closest wide landscape
    case '3:2': // Closest standard landscape
      return 'landscape_16_9';
    case '9:16':
    case '16:21': // Closest tall portrait
    case '2:3': // Closest standard portrait
      return 'portrait_16_9';
    case '4:3':
      return 'landscape_4_3';
    case '3:4':
      return 'portrait_4_3';
    default:
      console.warn(`Unsupported aspect ratio "${appAspectRatio}" for Qwen. Defaulting to "square".`);
      return 'square'; // Default to square if unknown
  }
};

/**
 * Helper to map app aspectRatio to Grok Imagine's supported aspect ratios.
 * Grok Imagine supports: 1:1, 2:3, 3:2
 */
export const mapToGrokImagineAspectRatio = (appAspectRatio: string): string => {
  switch (appAspectRatio) {
    case '3:2':
    case '16:9': // Map common wide landscape to 3:2
    case '21:9': // Map cinematic wide to 3:2
    case '4:3':  // Map standard landscape to 3:2
      return '3:2';
    case '2:3':
    case '9:16': // Map common tall portrait to 2:3
    case '16:21': // Map cinematic tall to 2:3
    case '3:4':  // Map standard portrait to 2:3
      return '2:3';
    case '1:1':
    default:
      return '1:1'; // Default to square if not explicitly mapped or unknown
  }
};


export const KieAiService = {
  getAvailableModels: async (): Promise<KieAiImageModel[]> => {
    await new Promise((resolve) => setTimeout(resolve, 500));

    const allModels: KieAiImageModel[] = [
      { id: 'kie-gemini-flash-image', name: '나노바나나 (gemini-2.5-flash-image)', description: '사실적인 이미지를 빠르게 생성합니다. 캐릭터 레퍼런스 및 편집 가능.' },
      { id: 'kie-gemini-pro-image', name: '나노바나나 프로 (gemini-3-pro-image-preview)', description: '고품질의 상세한 이미지를 생성합니다. 캐릭터 레퍼런스 및 편집 가능.' },
      { id: 'kie-imagen-4', name: 'Imagen 4.0 (imagen-4.0-generate-001)', description: '고급 이미지 생성 (Google API 아님). 캐릭터 레퍼런스 및 편집 가능.' },
      { id: 'kie-4o-image', name: '4o Image API (GPT-4o 기반)', description: 'GPT-4o 모델로 구동되는 고급 이미지 생성. (텍스트-투-이미지 및 단일 레퍼런스 이미지).' }, // Updated description
      { id: 'kie-flux-2-pro', name: 'Flux-2 Pro (Kontext-Pro)', description: 'Flux Kontext 고성능 모델. 텍스트-투-이미지, 이미지 편집, 이미지 기반 생성 모두 가능.' }, // Updated name
      { id: 'kie-seedream-4', name: 'Seedream 4.0 (Bytedance)', description: 'Seedream4.0의 고급 AI 모델로 구동되는 고품질 사실적인 이미지 생성. (텍스트-투-이미지 전용).' },
      { id: 'kie-midjourney', name: 'Midjourney (Kie.ai)', description: 'Kie.ai를 통해 Midjourney의 강력한 이미지 생성 기능을 사용합니다. (텍스트-투-이미지 전용).' }, // NEW: Midjourney Model
      { id: 'kie-z-image', name: 'Z-Image (Kie.ai)', description: 'Kie.ai의 Z-Image 모델을 사용한 빠르고 고품질 이미지 생성. (텍스트-투-이미지 전용).' }, // NEW: Z-Image Model
      { id: 'kie-grok-imagine', name: 'Grok Imagine (Kie.ai)', description: 'Kie.ai의 Grok Imagine 모델을 사용한 혁신적인 이미지 생성. (텍스트-투-이미지 전용).' }, // NEW: Grok Imagine Model
      { id: 'kie-qwen', name: 'Qwen AI (Kie.ai)', description: 'Kie.ai의 Qwen AI 모델을 사용한 텍스트-투-이미지 생성.' }, // UPDATED: Qwen AI Model to T2I
      // Mock models for others
      // { id: 'mock-grok-imagine', name: 'Grok Imagine (모의)', description: '혁신적인 아이디어를 시각화 (모의 서비스).' }, // REMOVED mock Grok Imagine
      // { id: 'mock-qwen', name: 'Qwen AI (모의)', description: '빠르고 효율적인 이미지 생성 (모의 서비스).' }, // REMOVED mock Qwen
    ];

    return allModels.sort((a, b) => {
        const realApiOrder = ['kie-gemini-flash-image', 'kie-gemini-pro-image', 'kie-imagen-4', 'kie-4o-image', 'kie-flux-2-pro', 'kie-seedream-4', 'kie-midjourney', 'kie-z-image', 'kie-grok-imagine', 'kie-qwen']; // Added Grok Imagine and Qwen
        const aIndex = realApiOrder.indexOf(a.id);
        const bIndex = realApiOrder.indexOf(b.id);
        if (aIndex !== -1 && bIndex === -1) return -1;
        if (aIndex === -1 && bIndex !== -1) return 1;
        if (aIndex !== -1 && bIndex !== -1) return aIndex - bIndex;
        return a.name.localeCompare(b.name);
    });
  },

  generateImage: async (
    textPrompt: string,
    modelId: string,
    width: number = 512, // These width/height are mostly for mock images now.
    height: number = 512, // Real APIs use aspectRatio + resolution.
    aspectRatio: string = '1:1',
    characterReferenceImages?: ReferenceImage[] | null, // CHANGED: now array of ReferenceImage
    imageToEdit?: { data: string; mimeType: string; } | null,
    imageQuality: string = '1K (표준)',
    geminiApiKey: string | null = null, // Re-added geminiApiKey
    kieAiApiKey: string | null = null, // Re-added kieAiApiKey
    // REMOVED characterReferenceImageFileName as it's now part of ReferenceImage
  ): Promise<KieAiImageGenerationResponse> => {
    
    console.log(`[Kie.ai Service] generateImage called for model: ${modelId}, prompt: "${textPrompt.substring(0, 50)}..."`);
    console.log(`[Kie.ai Service]   Gemini API Key present: ${!!geminiApiKey}`);
    console.log(`[Kie.ai Service]   Kie.ai API Key present: ${!!kieAiApiKey}`);


    try {
      // Handle mock models first, they don't require API keys
      if (modelId.startsWith('mock-')) {
        console.log(`[Mock Service] Generating mock image for model: ${modelId}`);
        await new Promise(resolve => setTimeout(resolve, 2000)); // Simulate loading
        return {
          imageUrl: getMockImageUrl(width, height, Math.floor(Math.random() * 100000)),
          model: modelId,
          prompt: textPrompt,
          isMock: true
        };
      }

      // API Key checks for real models
      // Check if geminiApiKey is provided for Google-backed models
      if ((modelId.startsWith('kie-gemini') || modelId.startsWith('kie-imagen')) && !geminiApiKey) {
        throw new Error("Gemini/Imagen 모델을 사용하려면 Gemini API 키가 필요합니다.");
      }
      // Check if kieAiApiKey is provided for Kie.ai-specific models
      if ((modelId === 'kie-4o-image' || modelId === 'kie-flux-2-pro' || modelId === 'kie-seedream-4' || modelId === 'kie-midjourney' || modelId === 'kie-z-image' || modelId === 'kie-grok-imagine' || modelId === 'kie-qwen') && !kieAiApiKey) {
        throw new Error("선택된 모델은 Kie.ai API 키가 필요합니다.");
      }

      // Fix: Instantiate GoogleGenAI client once if a Google-backed model is selected.
      // This ensures 'ai' is accessible for both Gemini and Imagen models.
      let ai: GoogleGenAI | null = null;
      if (modelId.startsWith('kie-gemini') || modelId.startsWith('kie-imagen')) {
        ai = new GoogleGenAI({ apiKey: geminiApiKey! });
      }

      // Prepare reference image URLs if any
      let uploadedReferenceImageUrls: string[] = []; // CHANGED to array
      let uploadedImageToEditUrl: string | null = null;

      // Prioritize imageToEdit if it exists, for explicit editing scenarios
      if (imageToEdit) {
        console.log('[Kie.aiService] Uploading image to edit...');
        // For imageToEdit, we don't have the original filename readily, so use a generic one
        uploadedImageToEditUrl = await uploadImageToKieAi(kieAiApiKey!, imageToEdit.data, imageToEdit.mimeType, `edited_image.${imageToEdit.mimeType.split('/')[1] || 'png'}`);
      } else if (characterReferenceImages && characterReferenceImages.length > 0) { // CHANGED: check array
        // If no explicit image to edit, check for character reference images
        console.log(`[Kie.aiService] Uploading ${characterReferenceImages.length} character reference image(s)...`);
        for (const refImage of characterReferenceImages) {
          const uploadedUrl = await uploadImageToKieAi(kieAiApiKey!, refImage.data, refImage.mimeType, refImage.fileName);
          uploadedReferenceImageUrls.push(uploadedUrl);
        }
      }


      // Handle Seedream 4.0 (now 4.5)
      if (modelId === 'kie-seedream-4') {
        if (characterReferenceImages && characterReferenceImages.length > 0 || imageToEdit) { // CHANGED: check array
          throw new Error("Seedream 4.5은 현재 텍스트-투-이미지만 지원합니다. 레퍼런스 이미지 또는 편집 기능은 사용할 수 없습니다.");
        }

        const mapImageQualityToKieAiSeedreamQuality = (quality: string): string => {
          const strippedQuality = quality.replace(' (표준)', '');
          if (strippedQuality.includes('4K')) return 'high'; // 4K maps to 'high'
          return 'basic'; // 1K, 2K map to 'basic'
        };

        const kieAiSeedreamQuality = mapImageQualityToKieAiSeedreamQuality(imageQuality);

        const inputPayload = {
          prompt: textPrompt,
          aspect_ratio: aspectRatio, // Use aspect_ratio directly from frontend
          quality: kieAiSeedreamQuality, // Map frontend quality to Kie.ai 'quality'
        };

        // Update model name to seedream/4.5-text-to-image as per documentation
        const resultUrls = await callKieAiGenericJobApi(kieAiApiKey!, 'seedream/4.5-text-to-image', inputPayload);

        return {
          imageUrl: resultUrls[0],
          model: modelId,
          prompt: textPrompt,
          isMock: false
        };
      }

      // Handle Midjourney (Kie.ai) - NEW
      if (modelId === 'kie-midjourney') {
        if (characterReferenceImages && characterReferenceImages.length > 0 || imageToEdit) { // CHANGED: check array
          throw new Error("Midjourney (Kie.ai)는 현재 텍스트-투-이미지만 지원합니다. 레퍼런스 이미지 또는 편집 기능은 사용할 수 없습니다.");
        }

        // Kie.ai Midjourney API doesn't seem to take 'resolution' in payload based on ui.py snippet
        // It directly uses aspectRatio and has a fixed 'fast' speed.
        const resultUrls = await callKieAiMidjourneyApi(kieAiApiKey!, textPrompt, aspectRatio);

        return {
          imageUrl: resultUrls[0],
          model: modelId,
          prompt: textPrompt,
          isMock: false
        };
      }

      // NEW: Handle Z-Image (Kie.ai)
      if (modelId === 'kie-z-image') {
        if (characterReferenceImages && characterReferenceImages.length > 0 || imageToEdit) { // CHANGED: check array
          throw new Error("Z-Image (Kie.ai)는 현재 텍스트-투-이미지만 지원합니다. 레퍼런스 이미지 또는 편집 기능은 사용할 수 없습니다.");
        }
        
        // --- PROMPT LENGTH VALIDATION FOR Z-IMAGE ---
        const Z_IMAGE_MAX_PROMPT_LENGTH = 1000;
        if (textPrompt.length > Z_IMAGE_MAX_PROMPT_LENGTH) {
          throw new Error(`Z-Image 모델은 프롬프트가 ${Z_IMAGE_MAX_PROMPT_LENGTH}자를 초과할 수 없습니다. 현재 ${textPrompt.length}자입니다. 프롬프트를 줄여주세요.`);
        }
        // --- END PROMPT LENGTH VALIDATION ---

        const inputPayload = {
          prompt: textPrompt,
          aspect_ratio: aspectRatio,
        };

        const resultUrls = await callKieAiGenericJobApi(kieAiApiKey!, 'z-image', inputPayload);

        return {
          imageUrl: resultUrls[0],
          model: modelId,
          prompt: textPrompt,
          isMock: false
        };
      }

      // NEW: Handle Grok Imagine (Kie.ai) - CORRECTED to use aspect_ratio and map it
      if (modelId === 'kie-grok-imagine') {
        if (characterReferenceImages && characterReferenceImages.length > 0 || imageToEdit) { // CHANGED: check array
          throw new Error("Grok Imagine (Kie.ai)는 현재 텍스트-투-이미지만 지원합니다. 레퍼런스 이미지 또는 편집 기능은 사용할 수 없습니다.");
        }
        
        // --- PROMPT LENGTH VALIDATION FOR GROK IMAGINE ---
        const GROK_IMAGINE_MAX_PROMPT_LENGTH = 5000;
        if (textPrompt.length > GROK_IMAGINE_MAX_PROMPT_LENGTH) {
          throw new Error(`Grok Imagine 모델은 프롬프트가 ${GROK_IMAGINE_MAX_PROMPT_LENGTH}자를 초과할 수 없습니다. 현재 ${textPrompt.length}자입니다. 프롬프트를 줄여주세요.`);
        }
        // --- END PROMPT LENGTH VALIDATION ---

        // Grok Imagine expects aspect_ratio directly, but must be within supported range.
        const mappedAspectRatio = mapToGrokImagineAspectRatio(aspectRatio);
        const inputPayload = {
          prompt: textPrompt,
          aspect_ratio: mappedAspectRatio, // CORRECTED: Pass mappedAspectRatio
        };

        const resultUrls = await callKieAiGenericJobApi(kieAiApiKey!, 'grok-imagine/text-to-image', inputPayload);

        return {
          imageUrl: resultUrls[0],
          model: modelId,
          prompt: textPrompt,
          isMock: false
        };
      }

      // UPDATED: Handle Qwen AI (Kie.ai) as T2I
      if (modelId === 'kie-qwen') {
        // --- T2I VALIDATION FOR QWEN ---
        if (characterReferenceImages && characterReferenceImages.length > 0 || imageToEdit) { // CHANGED: check array
          throw new Error("Qwen AI 모델은 현재 텍스트-투-이미지만 지원합니다. 레퍼런스 이미지 또는 편집 기능은 사용할 수 없습니다.");
        }
        // --- END T2I VALIDATION ---
        
        // --- PROMPT LENGTH VALIDATION FOR QWEN ---
        const QWEN_MAX_PROMPT_LENGTH = 5000;
        if (textPrompt.length > QWEN_MAX_PROMPT_LENGTH) {
          throw new Error(`Qwen AI 모델은 프롬프트가 ${QWEN_MAX_PROMPT_LENGTH}자를 초과할 수 없습니다. 현재 ${textPrompt.length}자입니다. 프롬프트를 줄여주세요.`);
        }
        // --- END PROMPT LENGTH VALIDATION ---

        // Use mapToQwenImageSize for Qwen
        const qwenImageSize = mapToQwenImageSize(aspectRatio, imageQuality);

        const inputPayload = {
          prompt: textPrompt,
          image_size: qwenImageSize, // Correctly use image_size for Qwen
          // Optional parameters with sensible defaults as per documentation
          num_inference_steps: 30,
          guidance_scale: 2.5,
          enable_safety_checker: true,
          output_format: 'png',
          acceleration: 'regular',
          // negative_prompt: 'blurry, ugly', // This is optional, can be added if we have a UI for it.
        };

        const resultUrls = await callKieAiGenericJobApi(kieAiApiKey!, 'qwen/text-to-image', inputPayload);

        return {
          imageUrl: resultUrls[0],
          model: modelId,
          prompt: textPrompt,
          isMock: false
        };
      }


      // --- NEW/UPDATED: Handle Flux-2 Pro using generic Kie.ai job API ---
      if (modelId === 'kie-flux-2-pro') {
        const fluxResolution = imageQuality.replace(' (표준)', ''); // 1K (표준) -> 1K

        let modelToUseForJobApi: string;
        const inputPayload: any = {
          prompt: textPrompt,
          aspect_ratio: aspectRatio,
          resolution: fluxResolution,
        };

        const imageInputUrls = uploadedImageToEditUrl ? [uploadedImageToEditUrl] : uploadedReferenceImageUrls; // If editing, use single imageToEdit URL, else all reference image URLs

        if (imageInputUrls && imageInputUrls.length > 0) {
          modelToUseForJobApi = 'flux-2/pro-image-to-image'; // I2I model name
          inputPayload.input_urls = imageInputUrls; // Pass as an array for I2I
          console.log('[Kie.aiService] Flux-2 Pro I2I with prompt:', textPrompt, 'and image URL(s):', imageInputUrls);
        } else {
          modelToUseForJobApi = 'flux-2/pro-text-to-image'; // T2I model name
          console.log('[Kie.aiService] Flux-2 Pro T2I with text prompt:', textPrompt);
        }

        const resultUrls = await callKieAiGenericJobApi(
          kieAiApiKey!,
          modelToUseForJobApi,
          inputPayload
        );

        return {
          imageUrl: resultUrls[0],
          model: modelId,
          prompt: textPrompt,
          isMock: false
        };
      }

      // Handle Gemini models
      if (modelId === 'kie-gemini-flash-image' || modelId === 'kie-gemini-pro-image') {
        const contentsParts: Part[] = [];

        if (imageToEdit) { // Existing image editing logic (single image)
          contentsParts.push({ inlineData: { data: imageToEdit.data, mimeType: imageToEdit.mimeType } });
          contentsParts.push({ text: textPrompt });
          console.log('[Kie.aiService] Gemini editing image with prompt:', textPrompt);
        } else if (characterReferenceImages && characterReferenceImages.length > 0) { // CHANGED: New generation with multiple reference images
          for (const refImage of characterReferenceImages) {
            contentsParts.push({ inlineData: { data: refImage.data, mimeType: refImage.mimeType } });
          }
          contentsParts.push({ text: textPrompt });
          console.log(`[Kie.aiService] Gemini generating with ${characterReferenceImages.length} character reference image(s) and prompt:`, textPrompt);
        } else { // New generation with text only
          contentsParts.push({ text: textPrompt });
          console.log('[Kie.aiService] Gemini generating with text prompt:', textPrompt);
        }

        const modelToUse = modelId === 'kie-gemini-flash-image' ? 'gemini-2.5-flash-image' : 'gemini-3-pro-image-preview';
        const config: any = { imageConfig: { aspectRatio: aspectRatio } };

        if (modelToUse === 'gemini-3-pro-image-preview') {
          config.imageConfig.imageSize = imageQuality.includes('2K') ? '2K' : (imageQuality.includes('4K') ? '4K' : '1K');
          // config.tools = [{googleSearch: {}}]; // Temporarily removed to prevent conflicts with imageConfig in some versions or for image generation models where it might not be relevant. Re-add if explicitly needed and stable.
        }

        const response: GenerateContentResponse = await ai!.models.generateContent({
          model: modelToUse,
          contents: { parts: contentsParts },
          config: config,
        });

        const imagePart = response.candidates?.[0]?.content?.parts?.find(p => p.inlineData);
        if (imagePart?.inlineData?.data) {
          console.log('[Kie.aiService] Gemini image generation successful.');
          return {
            imageUrl: `data:${imagePart.inlineData.mimeType};base64,${imagePart.inlineData.data}`,
            model: modelId,
            prompt: textPrompt,
            isMock: false
          };
        }
        throw new Error(`${modelToUse} 이미지 응답에서 데이터를 찾을 수 없습니다.`);
      }

      // Handle Imagen 4.0
      if (modelId === 'kie-imagen-4') {
        // Imagen 4.0 typically supports one primary image for I2I, so we'll use the first reference image if multiple are provided.
        // The check and alert for multiple images are now handled in App.tsx
        const imagenImagePayload = imageToEdit ? { imageBytes: imageToEdit.data, mimeType: imageToEdit.mimeType } : 
                                   (characterReferenceImages && characterReferenceImages.length > 0 ? { imageBytes: characterReferenceImages[0].data, mimeType: characterReferenceImages[0].mimeType } : undefined);

        const config: any = {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
          aspectRatio: aspectRatio,
          imageSize: imageQuality.includes('2K') ? '2K' : (imageQuality.includes('4K') ? '4K' : '1K')
        };
        
        console.log('[Kie.aiService] Imagen 4.0 generating with prompt:', textPrompt, 'and payload:', imagenImagePayload);
        const response = await ai!.models.generateImages({
          model: 'imagen-4.0-generate-001',
          prompt: textPrompt,
          image: imagenImagePayload,
          config: config,
        });
        if (response.generatedImages?.[0]?.image?.imageBytes) {
          console.log('[Kie.aiService] Imagen 4.0 image generation successful.');
          return {
            imageUrl: `data:image/jpeg;base64,${response.generatedImages[0].image.imageBytes}`,
            model: modelId,
            prompt: textPrompt,
            isMock: false
          };
        }
        throw new Error('Imagen 4.0 응답 결과가 비어있습니다.');
      }

      // Handle 4o Image
      if (modelId === 'kie-4o-image') {
        let apiSize = '1:1';
        if (aspectRatio === '16:9' || aspectRatio === '4:3' || aspectRatio === '21:9') apiSize = '3:2';
        else if (aspectRatio === '9:16' || aspectRatio === '3:4' || aspectRatio === '16:21') apiSize = '2:3';

        console.log('[Kie.aiService] 4o Image API generating with prompt:', textPrompt, 'and size:', apiSize, 'referenceImageUrls:', uploadedReferenceImageUrls);
        // 4o Image uses 'reference_images' (array) which is fine for single or multiple uploaded ref images.
        const resultUrls = await call4oImageApi(kieAiApiKey!, textPrompt, apiSize, 1, false, uploadedReferenceImageUrls); // CHANGED: pass array
        return {
          imageUrl: resultUrls[0],
          model: modelId,
          prompt: textPrompt,
          isMock: false
        };
      }

      throw new Error("지원하지 않는 모델입니다.");

    } catch (rawError: any) {
      console.error(`[Service Error - ${modelId}]:`, rawError); // Improved error logging
      let errorMessage = "알 수 없는 이미지 생성 오류가 발생했습니다.";

      // Attempt to parse API specific error format if it's a known object
      if (rawError && typeof rawError === 'object' && rawError.message) {
        errorMessage = rawError.message;
      } else if (rawError instanceof Error) {
        errorMessage = rawError.message;
      } else if (typeof rawError === 'string') {
        errorMessage = rawError;
      } else {
        errorMessage = JSON.stringify(rawError);
      }

      // The specific error handling logic from callKieAiGenericJobApi and other specific API calls
      // should already add context about API keys or internal errors.
      // We no longer add a generic ". API 키를 확인하세요." here, as it can be misleading.
      throw new Error(
        `이미지 생성 실패: ${errorMessage}`
      );
    }
  },

  /**
   * Checks the remaining credits for the Kie.ai API key.
   * @param apiKey The Kie.ai API key to check.
   * @returns An object indicating success, remaining credits, and a message.
   */
  checkKieAiCredits: async (apiKey: string): Promise<{ success: boolean; credits: number | null; message: string }> => {
    try {
      if (!apiKey.trim()) {
        return { success: false, credits: null, message: "API 키가 비어있습니다." };
      }

      console.log(`[Kie.ai Service] checkKieAiCredits called. API Key present: ${!!apiKey}`);

      const creditEndpoint = 'https://api.kie.ai/api/v1/chat/credit';
      const response = await fetch(creditEndpoint, {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json'
        }
      });

      const result = await response.json();
      console.log("[Kie.ai Credit Check] Response:", result);

      if (response.ok && result.code === 200 && typeof result.data === 'number') {
        return { success: true, credits: result.data, message: `남은 크레딧: ${result.data} (성공)` };
      } else {
        let errorMessage = result.msg || `알 수 없는 오류 (Code: ${result.code || response.status})`;
        if (result.code === 401) { // Unauthorized
          errorMessage = "Kie.ai API 키가 유효하지 않거나 인증에 실패했습니다. 올바른 키를 입력해주세요.";
        } else if (result.code === 402) { // Insufficient Credits (Kie.ai's specific code for this)
          errorMessage = "Kie.ai 크레딧이 부족합니다. 결제 페이지를 확인해주세요.";
        } else if (result.code === 429) { // Rate Limited
          errorMessage = "Kie.ai API 요청 한도를 초과했습니다. 잠시 후 다시 시도해주세요.";
        } else if (result.code === 500) { // Server Error
          errorMessage = "Kie.ai 서버 내부 오류입니다. 잠시 후 다시 시도해주세요.";
        }
        return { success: false, credits: result.data || null, message: `Kie.ai API 키 테스트 실패: ${errorMessage}` };
      }
    } catch (error: any) {
      console.error("Kie.ai API 키 테스트 중 오류 발생:", error);
      return { success: false, credits: null, message: `Kie.ai API 키 테스트 중 네트워크 오류 발생: ${error.message}` };
    }
  },
};